version: 2.1
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Install python versions
          command: pyenv local 3.5 3.6 3.7 3.8
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "dev-requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r dev-requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "dev-requirements.txt" }}
      - run:
          name: Lint code
          command: |
            . venv/bin/activate
            flake8
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            tox
  publish:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install sdist wheel twine
      - run:
          name: Verify version matches git tag
          command: |
            . venv/bin/activate
            python setup.py verify
      - run:
          name: Build package
          command: |
            . venv/bin/activate
            python setup.py sdist
            python setup.py bdist_wheel
      - run:
          name: Upload to PyPI
          command: |
            . venv/bin/activate
            twine upload dist/*
